### ISSUE TITLE
two Pods ` spdkcsi-controller-0` and `spdkcsi-node-xxxxx`  restart

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#10]
One more question I'd like to ask you, When all the components are running， and the two Pods ` spdkcsi-controller-0` and `spdkcsi-node-xxxxx` hang up, the previously applied PVC resources and mounting information are lost, and the command `kubectl delete -f testpod.yaml` cannot be passed to stop. And after executing this command, Pod `spdkcsi-test ` has been in Terminating state.Have you considered this question?

My understanding is that when applying for resources, all valid information is stored in the cache. When two Pods hang up, the information in the cache is lost. After restarting the two Pods, there is no previous information. So I can't stop testpod.

**Comment by lijhnihaoa** [comment]
Maybe this is my problem

**Comment by cyb70289** [comment]
@lijhnihaoa will you close this issue?

**Comment by lijhnihaoa** [comment]
I'm sorry，I think this might be a problem. If the CSI plugin unexpectedly hangs and Kubelet pulls the CSI plugin up, the volume information that was previously managed will be lost and the volume that was previously managed will become unmanageable

**Comment by lijhnihaoa** [comment]
Is there any way to retrieve the information of previously managed volumes after a plug-in is disconnected.

**Comment by cyb70289** [comment]
Currently, no.
We need adding durability support to recover from plugin restart.

**Comment by lijhnihaoa** [comment]
I saw the processing of ceph-csi, they are to save the uninstallation related information to the hostPath. Read this file when uninstalling, according to them, they don't save any useful information to the CSI driver

**Comment by lijhnihaoa** [comment]
Maybe we can learn from this
