### ISSUE TITLE
why not a device-plugin

### ISSUE THREAD

**Issue by weiwei04** [spdk/spdk-csi#11]
SDPK with nvme is like a user space driver + raw device, why not use device plugin to allocate and initialize nvme device(like gpu)

The main difference between a storage device and computing device is storage device are stateful, when pod recreated it should bind to the original allocated device. 

If the pod scheduler and device plugin can persist the pod to nvme device mapping, I'm not sure if there are any other technical issues that we can't use a device plugin to setup spdk in kubernetes?

**Comment by cyb70289** [comment]
I think CSI and device plugin are very different.
IIUC, your point of device plugin is to deploy SPDK services on nodes with NVMe devices.
The use case of SPDK-CSI, on the other hand, is to enable pod to use SPDK powered volumes (through network) automatically.
E.g., There is an existing SPDK cluster deployed, connected to kubernetes cluster through RDMA or TCP networking. A pod is created in kubernetes, which requires an SPDK backed volume. SPDK-CSI will send commands to SPDK cluster to create the required volume on demand, export it by SPDK NVMe-oF target module. Then mount the target as a local block device (the volume is at remote) by running nmve initiator commands on the pod node. Finally the volume is mounted inside the pod.

**Comment by weiwei04** [comment]
Thanks, I get the differences. spdk-csi is for SPDK-Volume as a Service.
