### ISSUE TITLE
one  idea

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#12]
I thought of a way to combine the lvolID into rpcUrl-username-userpass-uuid, so that the key information can be stored in k8s, so that if you want to DeleteVolume, you can use the previous three information to form a client to check and Delete lvolid, do you think this will work?

**Comment by cyb70289** [comment]
This might work, but it's more like a temporary workaround. Not recommended in practice.

**Comment by lijhnihaoa** [comment]
```
0001 -->                              [csi_id_version=1:4byte] + [-:1byte]
0009 -->                              [length of clusterID=1:4byte] + [-:1byte]
rook-ceph -->                         [clusterID:36bytes (MAX)] + [-:1byte]
0000000000000002 -->                  [poolID:16bytes] + [-:1byte]
b0285c97-a0ce-11eb-8c66-0242ac110002 --> [ObjectUUID:36bytes]
Total of constant field lengths, including '-' field separators would hence be,
4+1+4+1+1+16+1+36 = 64
```
But csph-csi is implemented like this

**Comment by lijhnihaoa** [comment]
https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/clusterid-mapping.md

**Comment by cyb70289** [comment]
It's okay to encode some storage backend info into volume id, e.g., rpcUrl is probably okay. But secrets like username and password are not suitable.

**Comment by cyb70289** [comment]
I think spdk volume id can be used, like objectuuid in the ceph proposal.

**Comment by lijhnihaoa** [comment]
Why is the username and password inappropriate? If the controller plugin is restarted, the spdkNode corresponding to the volume cannot be initialized without the username and password, right?

```
func deleteVolume(volume *volume) error {
	return volume.**spdkNode**.DeleteVolume(volume.csiVolume.GetVolumeId())
}

func unpublishVolume(volume *volume) error {
	return volume.**spdkNode**.UnpublishVolume(volume.csiVolume.GetVolumeId())
}
```

**Comment by cyb70289** [comment]
I mean it's secret, should not be in a volume id, which is publicly visible.

**Comment by lijhnihaoa** [comment]
When the newControllerServer is initialized, the username and password are not saved, so if you don't encode them into lvolid, there is nowhere to get this information unless you read secret.yaml

**Comment by lijhnihaoa** [comment]
> 我的意思是它是秘密的，不应该在公开可见的卷 ID 中。

Yes, what you said makes sense

**Comment by lijhnihaoa** [comment]
When executing newControllerServer, it may be a better way to make a map of rpcUrl and secret.
