### ISSUE TITLE
about external-resizer

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#15]
I want to add the volume expansion function on this basis, but after adding the v1.4.0 version of external-resizer, I found that
`updatedPVC, err := ctrl.patchClaim(pvc, newPVC, true /* addResourceVersionCheck */)` This function reports an error, the reason for the error` Error syncing PVC: marking pvc "kube-csi/volume-pvc" as resizing failed: can' t patch status of PVC kube-csi/volume-pvc with persistentvolumeclaims "volume-pvc" is forbidden`, I judge that the version may be too high and not suitable, may I ask is this the reason?

**Comment by lijhnihaoa** [comment]
`updatedClaim, updateErr := ctrl.kubeClient.CoreV1().PersistentVolumeClaims(oldPVC.Namespace).
		Patch(context.TODO(), oldPVC.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")
	if updateErr != nil {
		return oldPVC, fmt.Errorf("can't patch status of  PVC %s with %v", util.PVCKey(oldPVC), updateErr)
	}`

**Comment by lijhnihaoa** [comment]
the reason for the error `Error syncing PVC: marking pvc "kube-csi/volume-pvc" as resizing failed: can't patch status of  PVC kube-csi/volume-pvc with persistentvolumeclaims "volume-pvc" is forbidden: User "system:serviceaccount:kube-csi:spdkcsi-controller-sa" cannot patch resource "persistentvolumeclaims/status" in API group "" in the namespace "kube-csi"`

**Comment by cyb70289** [comment]
Not familiar with external-resize buut this looks like rbac configuration issue. We might need additional cluster roles such as `persistentvolumeclaims/status`.
You can compare below code with external-resizer document for possible missing roles.
https://github.com/spdk/spdk-csi/blob/master/deploy/kubernetes/controller-rbac.yaml

**Comment by lijhnihaoa** [comment]
You reminded me, thanks for giving me direction to think.

**Comment by lijhnihaoa** [comment]
When I configure the size of the created volume in yaml, I find that the unit of the volume is MiB. I want to know where you converted MiB into Bytes. When I change the volume size to trigger volume expansion, I find that the passed down size is not converted into bytes. 

`(gdb) b vbdev_lvol_create
Breakpoint 1 at 0x41e83f: file vbdev_lvol.c, line 1044.
(gdb) c
Continuing.

Breakpoint 1, vbdev_lvol_create (lvs=0x1c99970, name=0x30f2010 "csi-4c85dbe4-d890-4376-920c-f020501fc472", sz=88080384, thin_provision=true, clear_method=LVOL_CLEAR_WITH_UNMAP, cb_fn=0x42005a <rpc_bdev_lvol_create_cb>, cb_arg=0x1c9b780) at vbdev_lvol.c:1044
1044    vbdev_lvol.c: 没有那个文件或目录.
(gdb) up
#1  0x00000000004202be in rpc_bdev_lvol_create (request=0x1c9b780, params=0x1c94910) at vbdev_lvol_rpc.c:384
384    vbdev_lvol_rpc.c: 没有那个文件或目录.
(gdb) p req
$1 = {uuid = 0x0, lvs_name = 0x1c95ca0 "lvs0", lvol_name = 0x30f2010 "csi-4c85dbe4-d890-4376-920c-f020501fc472", size = 88080384, thin_provision = true, clear_method = 0x21d7da0 "unmap"}
(gdb) p params
$2 = (const struct spdk_json_val *) 0x1c94910
(gdb) p *params
$3 = {start = 0x22828ae, len = 10, type = SPDK_JSON_VAL_OBJECT_BEGIN}
(gdb) p *params.start
Attempt to dereference a generic pointer.
(gdb) p *params[10]
Structure has no component named operator*.
(gdb) p *params[11]
Structure has no component named operator*.
(gdb) p param.st
Display all 198 possibilities? (y or n)
(gdb) p param..start
No symbol "param" in current context.
(gdb) p params..start
A syntax error in expression, near `.start'.
(gdb) p params.start
$4 = (void *) 0x22828ae
(gdb) p params.start[0]
Attempt to dereference a generic pointer.
(gdb) p (char *)params.start[8]
Attempt to dereference a generic pointer.
(gdb) p (char *)params.start[0]
Attempt to dereference a generic pointer.
(gdb) p (char *)params.start
$5 = 0x22828ae "{\"lvol_name\":\"csi-4c85dbe4-d890-4376-920c-f020501fc472\",\"size\":88080384,\"lvs_name\":\"lvs0\",\"clear_method\":\"unmap\",\"thin_provision\":true}}"
(gdb) c
Continuing.

Breakpoint 1, vbdev_lvol_create (lvs=0x1c99970, name=0x1c98f00 "csi-a515aec1-ae34-4e81-ba1a-2b6145b06cbc", sz=88080384, thin_provision=true, clear_method=LVOL_CLEAR_WITH_UNMAP, cb_fn=0x42005a <rpc_bdev_lvol_create_cb>, cb_arg=0x1c9b780) at vbdev_lvol.c:1044
1044    vbdev_lvol.c: 没有那个文件或目录.
(gdb) info b
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x000000000041e83f in vbdev_lvol_create at vbdev_lvol.c:1044
    breakpoint already hit 2 times
(gdb) d 1
(gdb) b vbdev_lvol_resize
Breakpoint 2 at 0x41eca0: file vbdev_lvol.c, line 1167.
(gdb) c
Continuing.

Breakpoint 2, vbdev_lvol_resize (lvol=0x3924c00, sz=88, cb_fn=0x420f7a <rpc_bdev_lvol_resize_cb>, cb_arg=0x1c9b780) at vbdev_lvol.c:1167
1167    in vbdev_lvol.c
(gdb) up
#1  0x000000000042115a in rpc_bdev_lvol_resize (request=0x1c9b780, params=0x260d220) at vbdev_lvol_rpc.c:812
812    vbdev_lvol_rpc.c: 没有那个文件或目录.
(gdb) p (char *)params.start
$6 = 0x22815ae "{\"name\":\"28e80413-7eba-4439-97a1-c96a321da43f\",\"size\":88}}"`

**Comment by cyb70289** [comment]
@lijhnihaoa It will be great if you want to upstream new features to spdk-csi project.
