### ISSUE TITLE
snapshot and clone

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#19]
spdk-csi does not yet support cloning a volume using snapshots, and does not support cloning another volume directly, is that right?

**Comment by cyb70289** [comment]
yes

**Comment by lijhnihaoa** [comment]
To clone another volume directly, my development idea for this function is to temporarily create a snapshot, and use bdev_lvol_clone to delete the temporary snapshot after the clone is completed. Do you think it is possible?

**Comment by cyb70289** [comment]
I'm not familiar with spdk snapshot and clone.
It's better to ask this question at spdk mail list, there will be more useful advices from related specialists.

**Comment by lijhnihaoa** [comment]
OK, thanks
