### ISSUE TITLE
timed out waiting device ready:

### ISSUE THREAD

**Issue by 17856506926** [spdk/spdk-csi#24]
when i deploy spdk-test,its status always be "ContainerCreating"
![image](https://user-images.githubusercontent.com/126157441/220891117-9741cf20-0b79-4133-927e-a52ef5c50055.png)
and the describe say "MountVolume.MountDevice failed for volume "pvc-114cc322-8a71-4a11-be1a-2970bd11cf4c" : rpc error: code = Internal desc = timed out waiting device ready: /dev/disk/by-id/*df8f0a4e-1458-488b-8793-ed2222c0f25d*"
![image](https://user-images.githubusercontent.com/126157441/220891238-f0353828-fe85-4ddf-a091-7dc59f763cfb.png)
how can i fix it?

i did just like the guide test,except use my own kubernates not minikube.

and the "dmsg" show 
![image](https://user-images.githubusercontent.com/126157441/221074987-fe7b86d1-f87b-4742-907b-8ea015784ee4.png)

**Comment by xinydev** [comment]
Please provide more detailed information, such as the reproduction steps, how you installed spdk-csi step by step, and the logs of each pod of the spdk-csi driver.

Detailed information will help to locate where the problem is.

**Comment by 17856506926** [comment]
> Please provide more detailed information, such as the reproduction steps, how you installed spdk-csi step by step, and the logs of each pod of the spdk-csi driver.
> 
> Detailed information will help to locate where the problem is.

the pod can not start,the only log i can get is from "dmsg",it show "failed to connect socket"

**Comment by xinydev** [comment]
Did you run the [initialization of spdk](https://github.com/spdk/spdk-csi/blob/master/deploy/spdk/README.md) on the k8s nodo where you run testpod? If so, could you please paste the output of each step?

**Comment by lijhnihaoa** [comment]
nvme connect的时候失败了，你看一下spdk端是不是有什么报错日志.

**Comment by jimharris** [comment]
> nvme connect的时候失败了，你看一下spdk端是不是有什么报错日志.

Google Translate says:  The nvme connect failed, please check if there is any error log on the spdk side.

But please in the future, use English on SPDK GitHub issues.

Thanks,

Jim

**Comment by lijhnihaoa** [comment]
> > nvme connect的时候失败了，你看一下spdk端是不是有什么报错日志.
> 
> Google Translate says: The nvme connect failed, please check if there is any error log on the spdk side.
> 
> But please in the future, use English on SPDK GitHub issues.
> 
> Thanks,
> 
> Jim

OK， 
The reason is that when the remote volume fails to be connected to the local volume, no file with uuid is generated in the corresponding path. Therefore, when the disk is in use, the query cannot be performed and the wait times out.

**Comment by lijhnihaoa** [comment]
`kubectl log -f  xx` Check the controller-0 container log. There should be an error.
