### ISSUE TITLE
SPDK environment /root/spdk/scripts/rpc.py bdev_malloc_create issue

### ISSUE THREAD

**Issue by halfzebra** [spdk/spdk-csi#3]
I know this is not really an issue with this repository, but it looks like scripts SPDK `v20.01` can't run on the latest Python version(3.9.5).

So it looks like `sudo docker exec -it spdkdev /root/spdk/scripts/rpc.py bdev_malloc_create -b Malloc0 1024 4096` script fails with:

```bash
Traceback (most recent call last):
  File "/root/spdk/scripts/rpc.py", line 2340, in <module>
    call_rpc_func(args)
  File "/root/spdk/scripts/rpc.py", line 2311, in call_rpc_func
    args.func(args)
  File "/root/spdk/scripts/rpc.py", line 256, in bdev_malloc_create
    print_json(rpc.bdev.bdev_malloc_create(args.client,
  File "/root/spdk/scripts/rpc/bdev.py", line 184, in bdev_malloc_create
    return client.call('bdev_malloc_create', params)
  File "/root/spdk/scripts/rpc/client.py", line 151, in call
    response = self.recv()
  File "/root/spdk/scripts/rpc/client.py", line 123, in recv
    start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

The reason for this is:

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)
> https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals

The _workaround_ I'm using right now is to run `sed -i 's/clock/perf_counter/g' /root/spdk/scripts/rpc/client.py` before running the script.

I might be missing something, but Imy best guesses for possible solutions are:
- Update the SPDK version used in the image to the later one
  **Risks:** untested
- Run `sed -i 's/clock/perf_counter/g' /root/spdk/scripts/rpc/client.py` if the version is `v20.01`
  **Risks:** fragile, also needs to cover `v20.01-v20.04`
- Downgrade Python version if running `v20.01-v20.04`
   **Risks:** may need lots of extra deps and logic if using Anaconda

Is there a simpler solution to this?

Let me know what you think!

**Comment by cyb70289** [comment]
IMHO, upgrading to latest spdk release (tag v21.04) is the best choice.

**Comment by halfzebra** [comment]
Thanks for your feedback!

I've created a PR to address this.
