### ISSUE TITLE
When I hung on the file system, I found that the file system is bad

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#31]
cat /etc/redhat-release
CentOS Linux release 7.7.1908 (BonusCloud) 1688368866
`
package main

import (
	"fmt"
	"k8s.io/utils/mount"
	"k8s.io/utils/exec"
)

func main() {

	mntFlags := []string{}
	mounter := mount.SafeFormatAndMount{Interface: mount.New(""), Exec: exec.New()}
	err := mounter.FormatAndMount("/dev/nvme0n1", "/data", "ext4", mntFlags)
	if err != nil {
		fmt.Println("---:", err)
	}
}`

[root@node2 src]# go run test.go
I0830 18:09:37.757907    1646 mount_linux.go:367] Disk "/dev/nvme0n1" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/nvme0n1]
I0830 18:09:37.841104    1646 mount_linux.go:377] Disk successfully formatted (mkfs): ext4 - /dev/nvme0n1 /data
[root@node2 src]# blkid  -p -s TYPE  -s PTTYPE -o export  /dev/nvme0n1
[root@node2 src]# lsbkl
-bash: lsbkl: 未找到命令
[root@node2 src]# lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1 259:0    0    64M  0 disk /data
sda       8:0    0 111.3G  0 disk
├─sda2    8:2    0  11.1G  0 part
├─sda3    8:3    0    50G  0 part /
└─sda1    8:1    0     1G  0 part /boot
[root@node2 src]# blkid  -p -s TYPE  -s PTTYPE -o export  /dev/nvme0n1
[root@node2 src]#

**Comment by lijhnihaoa** [comment]
I found that if the disk is relatively large, it is no problem. For example, when the size of the disk exceeds 700M, there is no problem. If the size is less than or equal to 600M, there will be a problem of no file system. There is no test between 600 and 700. Don't know what causes this.

**Comment by xinydev** [comment]
Can you explain the relationship between this and spdk-csi? Also, the steps to reproduce the issue?

**Comment by lijhnihaoa** [comment]
It really doesn't matter. I just discovered this problem when I was using spdk-csi, and then wrote a simple code to test it. Let's see if anyone has the same problem as me
