### ISSUE TITLE
go1.22 compilation errors

### ISSUE THREAD

**Issue by glimchb** [spdk/spdk-csi#37]
with `make all` I see:
```
e2e/utils.go:397:2: undefined: Expect (typecheck)
        Expect(podList.Items).NotTo(BeNil())
        ^
pkg/spdk/controllerserver.go:114:33: cs.Driver undefined (type *controllerServer has no field or method Driver) (typecheck)
                for _, accessMode := range cs.Driver.GetVolumeCapabilityAccessModes() {
                                            ^
[10:39](https://delloneisg.slack.com/archives/D0471QVCZF0/p1708097963495949)
pkg/util/opiinitiator_test.go:43:12: m.Called undefined (type *MockNvmeRemoteControllerServiceClient has no field or method Called) (typecheck)
        args := m.Called(ctx, in)
                  ^
[10:40](https://delloneisg.slack.com/archives/D0471QVCZF0/p1708098000309789)
pkg/util/opiinitiator_test.go:179:12: i.Called undefined (type *MockFrontendNvmeServiceClient has no field or method Called) (typecheck)
        args := i.Called(ctx, in)
../../../usr/local/go/src/compress/flate/inflate.go:720:18: f.r.ReadByte undefined (type Reader has no field or method ReadByte) (typecheck)
                        c, err := f.r.ReadByte()
                                      ^
../../../usr/local/go/src/encoding/json/encode.go:427:4: e.WriteString undefined (type *encodeState has no field or method WriteString) (typecheck)
        e.WriteString("null")
```

**Comment by ehaligow** [comment]
Hi, @glimchb 

I investigated the issue and have some ideas what is causing the errors. According to section[ Why-do-you-have-typecheck-errors](https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors), I narrowed down the potential causes to the those two:
		
1. If using CGO, ensure all require system libraries are installed.
Try to run golangcli-lint with CGO_ENABLED=0, the same way go build is called.

2. Ensure the version of golangci-lint is built with a compatible version of Go.
During make, the following version is installed and used **golangci-lint 1.52.2 built with go1.20.2**. If you are using go 1.22, try installing newer version of golangci-lint, that will be compatible with the go you are using.
		
However, the newest version on golangci-lint has much more [linters, thar are disabled by default](https://golangci-lint.run/usage/linters/#disabled-by-default), than the one installed during make. The newly added linters, which are disabled by default, are enabled in config (in golangci.yml is set "endabled-all: true"). So, it will generate new issues. You can try to remove the setting from the config file, or add those linters to disable section. 
		
Can you please try those fixes, and let me know the result.

**Comment by ehaligow** [comment]
hi, @glimchb did you have a moment to take a look at my comment above?

**Comment by ehaligow** [comment]
hi, @glimchb could you take a look at proposed solutions?

**Comment by ehaligow** [comment]
Closing due to lack of response. Please reopen the issue if  the problem persists.

**Comment by ehaligow** [comment]
Closing due to lack of response. Please reopen the issue if the problem persists.
