### ISSUE TITLE
spdkcsi的镜像获取不到

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#6]
Failed to pull image "spdkcsi/spdkcsi:canary": rpc error: code = Unknown desc = Error response from daemon: pull access denied for spdkcsi/spdkcsi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by cyb70289** [comment]
There's no such image in dockerhub. You have to build it manually with `make image`.

**Comment by lijhnihaoa** [comment]
Yes, I've noticed that. I've got it up and running。
I changed the following two places：
testpod.yaml (storage: 64Mi)
docker exec -it spdkdev /root/spdk/scripts/rpc.py bdev_malloc_create -b Malloc0 128 4096

`root@lijh-virtual-machine:~# sudo docker exec -it spdkdev /root/spdk/scripts/rpc.py bdev_lvol_create_lvstore Malloc0 lvs0
46850755-5e2f-4d02-98b8-131f8877dd1c
root@lijh-virtual-machine:~# sudo docker exec -it spdkdev /root/spdk/scripts/rpc_http_proxy.py 127.0.0.1 9009 spdkcsiuser spdkcsipass
Started RPC http proxy server
`

When I try to test this out, execute this command：kubectl apply -f testpod.yaml。

`root@lijh-virtual-machine:~/spdk-csi/deploy/kubernetes# kubectl describe  pods spdkcsi-test
Name:         spdkcsi-test
Namespace:    default
Priority:     0
Node:         <none>
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  alpine:
    Image:      alpine:3
    Port:       <none>
    Host Port:  <none>
    Command:
      sleep
      365d
    Environment:  <none>
    Mounts:
      /spdkvol from spdk-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5sflq (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  spdk-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  spdkcsi-pvc
    ReadOnly:   false
  default-token-5sflq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5sflq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  5s (x4 over 2m28s)  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.`
`root@lijh-virtual-machine:~/spdk-csi/deploy/kubernetes# kubectl describe pvc
Name:          spdkcsi-pvc
Namespace:     default
StorageClass:  spdkcsi-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: csi.spdk.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    spdkcsi-test
Events:
  Type     Reason                Age                   From                                                    Message
  ----     ------                ----                  ----                                                    -------
  Normal   Provisioning          4m40s (x11 over 13m)  csi.spdk.io_node1_0f2b616d-4ede-44b3-b0a6-b98108aef164  External provisioner is provisioning volume for claim "default/spdkcsi-pvc"
  Warning  ProvisioningFailed    4m41s (x11 over 13m)  csi.spdk.io_node1_0f2b616d-4ede-44b3-b0a6-b98108aef164  failed to provision volume with StorageClass "spdkcsi-sc": rpc error: code = Internal desc = failed to find node with enough free space
  Normal   ExternalProvisioning  3m1s (x43 over 13m)   persistentvolume-controller                             waiting for a volume to be created, either by external provisioner "csi.spdk.io" or manually created by system administrator`

**Comment by lijhnihaoa** [comment]
I was wondering if you could give me some advice. Thank you very much

**Comment by lijhnihaoa** [comment]
I quite agree with you. I have created a volume, but nothing is available.

`./rpc.py bdev_lvol_get_lvstores
[
  {
    "uuid": "46850755-5e2f-4d02-98b8-131f8877dd1c",
    "name": "lvs0",
    "base_bdev": "Malloc0",
    "total_data_clusters": 31,
    "free_clusters": 31,
    "block_size": 4096,
    "cluster_size": 4194304
  }
]
`I feel very confused and do not know where there is a problem. I am a beginner, so I am sorry for the trouble.

**Comment by cyb70289** [comment]
We have a CI job to verify the whole workflow. It can be run inside a virtual machine with 8G memory.
I would suggest you follow the [CI test scripts](https://github.com/spdk/spdk-csi/tree/master/scripts/ci) to do a quick verification.
- launch a ubuntu or fedora vm
- run `prepare.sh` to install necessary packages
- run `test.sh` to do all the tests, including e2e test which starts spdk service, deploys k8s and verifies spdkcsi functions

**Comment by lijhnihaoa** [comment]
Thank you very much. I will build an environment for testing as you said

**Comment by cyb70289** [comment]
Can you close this issue?

**Comment by 17856506926** [comment]
> There's no such image in dockerhub. You have to build it manually with `make image`.

how to do that?

**Comment by cyb70289** [comment]
Do what it says `make image`

**Comment by 17856506926** [comment]
> Do what it says `make image`

sorry,i can not get you.do you mean "build image" by a dockerfile?but how can i get this docker file?

**Comment by junzeng1** [comment]
> make image

run "make image" under spdk-csi directory to build this spdkcsi/spdkcsi:canary locally.
