### ISSUE TITLE
kubectl apply -f testpod.yaml

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#7]
spdkcsi-test，The pods couldn't get up，STATUS is ContainerCreating。

kubectl describe po spdkcsi-test
`Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        111s               default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        110s               default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               108s               default-scheduler        Successfully assigned default/spdkcsi-test to host
  Normal   SuccessfulAttachVolume  109s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8a3aa437-a775-4a82-8e49-f1075d3b6e74"
  Warning  FailedMount             17s (x4 over 84s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-8a3aa437-a775-4a82-8e49-f1075d3b6e74" : rpc error: code = Internal desc = timed out waiting device ready: /dev/disk/by-id/*ddb26aa1-3a89-4354-9336-26e087ebb07d*`

**Comment by lijhnihaoa** [comment]
I think it was a reboot, but I couldn't find a solution. Hope to get your help

**Comment by lijhnihaoa** [comment]
I think it was the reboot that caused the problem, but I didn't find a solution. Hope to get your help

**Comment by lijhnihaoa** [comment]
root@host:~/spdk-csi/deploy/kubernetes# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
pvc-8a3aa437-a775-4a82-8e49-f1075d3b6e74   128Mi      RWO            Delete           Bound    default/spdkcsi-pvc   spdkcsi-sc              8m27s
root@host:~/spdk-csi/deploy/kubernetes# kubectl get pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
spdkcsi-pvc   Bound    pvc-8a3aa437-a775-4a82-8e49-f1075d3b6e74   128Mi      RWO            spdkcsi-sc     8m29s

**Comment by lijhnihaoa** [comment]
`root@host:~/spdk-csi/deploy/kubernetes# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
pvc-8a3aa437-a775-4a82-8e49-f1075d3b6e74   128Mi      RWO            Delete           Bound    default/spdkcsi-pvc   spdkcsi-sc              8m27s
root@host:~/spdk-csi/deploy/kubernetes# kubectl get pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
spdkcsi-pvc   Bound    pvc-8a3aa437-a775-4a82-8e49-f1075d3b6e74   128Mi      RWO            spdkcsi-sc     8m29s`

**Comment by cyb70289** [comment]
Thanks for evaluating spdkcsi and reporting issues.
Currently, spdkcsi internal status is not persistent. Rebooting (spdkcsi or spdk) will likely break existing deployment. I guess you have to delete the stale deployment and redeploy a new volume.
We have plan to support persistent status in spdkcsi. You are welcomed if you are interested and willing to contribute.

**Comment by lijhnihaoa** [comment]
`root@host:~/spdk-csi/deploy/kubernetes# kubectl get pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
spdkcsi-pvc   Bound    pvc-c2d4e13e-afab-4029-ba84-06a36191b7ee   256Mi      RWO            spdkcsi-sc     2m32s
root@host:~/spdk-csi/deploy/kubernetes# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
pvc-c2d4e13e-afab-4029-ba84-06a36191b7ee   256Mi      RWO            Delete           Bound    default/spdkcsi-pvc   spdkcsi-sc              2m34s`

I thought the problem was caused by improper operation, and since I couldn't solve it, I reset the VIRTUAL machine and rebuilt the environment. But I found it was not solved. After PVC and PV binding, I think `nvme0n1` disk should appear after executing `lsblk` command, so far I haven't found the cause.

**Comment by lijhnihaoa** [comment]
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               10m                  default-scheduler        Successfully assigned default/spdkcsi-test to host
  Normal   SuccessfulAttachVolume  10m                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-ae46ec85-61fe-4de8-864b-9fe3f07ebdfb"
  Warning  FailedMount             3m43s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[spdk-volume], unattached volumes=[default-token-4kjpc spdk-volume]: timed out waiting for the condition
  Warning  FailedMount             89s (x3 over 8m12s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[spdk-volume], unattached volumes=[spdk-volume default-token-4kjpc]: timed out waiting for the condition
  Warning  FailedMount             1s (x11 over 9m46s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-ae46ec85-61fe-4de8-864b-9fe3f07ebdfb" : rpc error: code = Internal desc = timed out waiting device ready: /dev/disk/by-id/*0bda3a4d-3235-403f-8e24-994eb148962e*

**Comment by lijhnihaoa** [comment]
`1209 02:45:00.635311       1 utils.go:73] GRPC call: /csi.v1.Node/NodeGetCapabilities
I1209 02:45:00.635337       1 utils.go:74] GRPC request: {}
I1209 02:45:00.635378       1 utils.go:79] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1209 02:45:00.639378       1 utils.go:73] GRPC call: /csi.v1.Node/NodeStageVolume
I1209 02:45:00.639392       1 utils.go:74] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-546d68d5-c147-435d-b4fd-5abe6a69d99c/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"fsType":"ext4","model":"f785aefc-e7c3-43a9-b475-a8d872287a5e","nqn":"nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e","storage.kubernetes.io/csiProvisionerIdentity":"1638952867479-8081-csi.spdk.io","targetAddr":"127.0.0.1","targetPort":"4420","targetType":"TCP"},"volume_id":"f785aefc-e7c3-43a9-b475-a8d872287a5e"}
I1209 02:45:00.639474       1 initiator.go:184] running command: [nvme connect -t tcp -a 127.0.0.1 -s 4420 -n nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e]
I1209 02:45:00.644129       1 initiator.go:192] command returned: Failed to parse ctrl info for "nqn=nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e,transport=tcp,traddr=127.0.0.1,trsvcid=4420"
E1209 02:45:00.644147       1 initiator.go:82] command [nvme connect -t tcp -a 127.0.0.1 -s 4420 -n nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e] failed: exit status 234
E1209 02:45:25.489640       1 utils.go:77] GRPC error: rpc error: code = Internal desc = timed out waiting device ready: /dev/disk/by-id/*f785aefc-e7c3-43a9-b475-a8d872287a5e*`

**Comment by lijhnihaoa** [comment]
kubectl logs spdkcsi-node-gzszp spdkcsi-node

I finally found the error here, but I haven't found a solution yet, so I don't know the specific reason for the error

**Comment by cyb70289** [comment]
Maybe the nvme target at spdk side is not started?
I would suggest re-testing in a clean environment. Teardown minikube, spdk container, reboot and try again.

**Comment by lijhnihaoa** [comment]
That was stupid. I missed the point. There is no ModProbe NVME-TCP module

**Comment by cyb70289** [comment]
Looks it's resolved? Can you close this issue?

**Comment by 17856506926** [comment]
> `1209 02:45:00.635311 1 utils.go:73] GRPC call: /csi.v1.Node/NodeGetCapabilities I1209 02:45:00.635337 1 utils.go:74] GRPC request: {} I1209 02:45:00.635378 1 utils.go:79] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]} I1209 02:45:00.639378 1 utils.go:73] GRPC call: /csi.v1.Node/NodeStageVolume I1209 02:45:00.639392 1 utils.go:74] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-546d68d5-c147-435d-b4fd-5abe6a69d99c/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"fsType":"ext4","model":"f785aefc-e7c3-43a9-b475-a8d872287a5e","nqn":"nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e","storage.kubernetes.io/csiProvisionerIdentity":"1638952867479-8081-csi.spdk.io","targetAddr":"127.0.0.1","targetPort":"4420","targetType":"TCP"},"volume_id":"f785aefc-e7c3-43a9-b475-a8d872287a5e"} I1209 02:45:00.639474 1 initiator.go:184] running command: [nvme connect -t tcp -a 127.0.0.1 -s 4420 -n nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e] I1209 02:45:00.644129 1 initiator.go:192] command returned: Failed to parse ctrl info for "nqn=nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e,transport=tcp,traddr=127.0.0.1,trsvcid=4420" E1209 02:45:00.644147 1 initiator.go:82] command [nvme connect -t tcp -a 127.0.0.1 -s 4420 -n nqn.2020-04.io.spdk.csi:uuid:f785aefc-e7c3-43a9-b475-a8d872287a5e] failed: exit status 234 E1209 02:45:25.489640 1 utils.go:77] GRPC error: rpc error: code = Internal desc = timed out waiting device ready: /dev/disk/by-id/*f785aefc-e7c3-43a9-b475-a8d872287a5e*`

hello,i have the same question like you,can you tell me where did you find this logs?thank you
