### ISSUE TITLE
It could be a bug

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#8]
`[2021-12-10 08:30:24.880721] ctrlr.c:2400:nvmf_ctrlr_identify: *ERROR*: Identify command with unsupported CNS 0x06`
I didn't use minikube, I used the standalone K8S environment. When I created testPod, there was an error on the SPDK side. Although it does not affect disks mounted to Pod, I would like to mention this issue, which may be a bug and may have problems in the future.
After my test, this error will be reported after the PVC is created and the `nvme connect` command is successfully connected.

**Comment by cyb70289** [comment]
Thanks for the report.

**Comment by cyb70289** [comment]
This message is from spdk code:
https://github.com/spdk/spdk/blob/91bd8744a901a916fc609b7ddce103633633d160/lib/nvmf/ctrlr.c#L2741
Not sure what it stands for, but from the code looks it's allowed to fail. And it's an INFO, not ERROR.

**Comment by lijhnihaoa** [comment]
I see "*ERROR*" giving me this illusion.Nice talking to you.

**Comment by cyb70289** [comment]
Thanks @lijhnihaoa to evaluate spdk-csi and report/fix errors.
May I ask your use cases about spdk-csi?
Only for experiment or there are actual requirements from your company maybe?

**Comment by lijhnihaoa** [comment]
There are other requirements, and your open source program gives me a learning demo.

**Comment by lijhnihaoa** [comment]
I have not used CSI and K8S before and have gone programming. After learning your open source code, I will do CSI development requirements in the future

**Comment by lijhnihaoa** [comment]
Thank you very much for your open source code and communication with you

**Comment by lijhnihaoa** [comment]
Thank you very much for your open source code and communication with you, as well as your help.
