### ISSUE TITLE
Questions about formatting and mounting

### ISSUE THREAD

**Issue by lijhnihaoa** [spdk/spdk-csi#9]
1. After applying for the PVC resource, NVMe disks are displayed on the host
2.NodeStageVolume The path is changed when the disk is being formatted
3.NodePublishVolume is actually mounted in Pod

    What I don’t understand is the path change in the second step when the disk is formatted, instead of directly mounting to the Pod.

func (ns *nodeServer) stageVolume(devicePath string, req *csi.NodeStageVolumeRequest) (string, error):
`	klog.Infof("mount %s to %s, fstype: %s, flags: %v", devicePath, stagingPath, fsType, mntFlags)
	mounter := mount.SafeFormatAndMount{Interface: ns.mounter, Exec: exec.New()}
	err = mounter.FormatAndMount(devicePath, stagingPath, fsType, mntFlags)` and
func (ns *nodeServer) publishVolume(stagingPath string, req *csi.NodePublishVolumeRequest) error:
`klog.Infof("mount %s to %s, fstype: %s, flags: %v", stagingPath, targetPath, fsType, mntFlags)
	return ns.mounter.Mount(stagingPath, targetPath, fsType, mntFlags)`
Wouldn't it be better to format and mount directly to the Pod? emmmm,I find it very difficult to understand. Can you answer this doubt?

**Comment by cyb70289** [comment]
There may be two pods on same work node wanting to access a same volume (in readonly mode). Directly mounting volume to a pod make it hard to handle this sharing use case.
So there's an indirection here to address the issue. Firstly mount to the work node, then bind mount to pods. This behaviour is defined by CSI spec.

**Comment by lijhnihaoa** [comment]
That means that the real mount is implemented in NodeStageVolume, and the Pod is only bound to the path of the mount(in readonly mode), It is equivalent to mapping the disk mounted to the worker node to two Pods, can I understand it this way?

**Comment by cyb70289** [comment]
Yes. But please note pod can bind mount to host path as readwrite, not limited to readonly.

**Comment by lijhnihaoa** [comment]
You are right, i agree
